### PR TITLE
Added a Menu Driven Program

### PR DESCRIPTION
**Pull request by KrishRathod**

### CODE REVIEW

**Comment by Asher-MS** [comment]
please elaborate the name of the program

**Review by ashermatsh — CHANGES_REQUESTED** [review]
please elaborate the name of the program

**Comment by KrishRathod** [comment]
> please elaborate the name of the program

This a Menu Driven Program using Switch case.
With the help of this program one can find the factorial of a number, whether a number is prime or not , odd and even number.

**Comment by ashermatsh** [comment]
please change the name of the program to explain what this program does

**Comment by KrishRathod** [comment]
> please change the name of the program to explain what this program does

Menu Driven Program using Switch case to calculate: 1.Factorial of a number 2.Prime Number 3. Find Number is odd or even.c 
Should this name will be ok? Or else you can suggest me one

**Comment by ashermatsh** [comment]
ok that would be nice

**Comment by KrishRathod** [comment]
> ok that would be nice

Done, Thanks for the help.
Hope you accept and merge it.

**Review by ashermatsh — APPROVED** [review]
Thank you for the contribution

**Pull request merged**
